//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturador_CTECAM_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int ID { get; set; }
        public string USUARIO_CREADOR_FACTURA { get; set; }
        public string FORMATO_FACTURA { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public string TIPO_FACTURA { get; set; }
        public string NCF_FACTURA { get; set; }
        public System.DateTime FECHA_FACTURA { get; set; }
        public string COMPANIA_RECEPTOR { get; set; }
        public Nullable<long> RNC_RECEPTOR { get; set; }
        public string PERSONA_ESPECIFICA_RECEPTOR { get; set; }
        public string ASUNTO_FACTURA { get; set; }
        public string DESCRIPCION_GENERAL_FACTURA { get; set; }
        public string DESCRIPCION_DESGLOZADA_FACTURA { get; set; }
        public Nullable<double> SUBTOTAL_FACTURA { get; set; }
        public Nullable<double> ITBIS_FACTURA { get; set; }
        public Nullable<double> ITBIS_MIN30_FACTURA { get; set; }
        public Nullable<double> TOTAL_FACTURA { get; set; }
        public Nullable<double> TOTAL_FINAL { get; set; }
    }
}
