//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturador_CTECAM_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCF
    {
        public int Id { get; set; }
        public string NCF_TYPENUMBER { get; set; }
        public string NCF_TYPEDESCRIPTION { get; set; }
    }
}
